// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Watchlist.Models;

public partial class Aspnetrole
{
    public string Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Aspnetuser> Users { get; set; } = new List<Aspnetuser>();
}