// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Watchlist.Models;

public partial class Series
{
    public string Name { get; set; }

    public int IdSeries { get; set; }

    public int IdCategory { get; set; }

    public string Description { get; set; }

    public string CurrentlyAt { get; set; }

    public virtual Category IdCategoryNavigation { get; set; }
}